services:
  sqlite:
    build:
      dockerfile: Dockerfile
    container_name: sqlite
    expose:
      - 8191
    volumes:
      - ./sqlite:/db
    command: ["tail", "-f", "/dev/null"]
    networks:
      - proxy

networks:
  proxy:
    external: true
